CREATE TABLE client (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL CONSTRAINT namechk CHECK(char_length(name) >= 3)
);

CREATE TABLE planet (
    ID VARCHAR(1000) PRIMARY KEY,
    NAME VARCHAR(500) NOT NULL CONSTRAINT namechk CHECK(char_length(name) >= 1)
);

CREATE TABLE ticket (
    ID INT GENERATED ALWAYS AS IDENTITY,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP(2),
    CLIENT_ID  INT,
	FROM_PLANET_ID VARCHAR(100),
	TO_PLANET_ID VARCHAR(100),
	FOREIGN KEY(CLIENT_ID ) REFERENCES CLIENT(ID) ON DELETE CASCADE,
	FOREIGN KEY(FROM_PLANET_ID) REFERENCES PLANET(ID) ON DELETE CASCADE,
	FOREIGN KEY(TO_PlANET_ID) REFERENCES PLANET(ID) ON DELETE CASCADE
);


